# Generated by Django 6.0.6 on 2026-07-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("career", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("career_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("skills", models.TextField()),
                ("courses", models.TextField()),
                ("jobs", models.TextField()),
                ("salary", models.CharField(max_length=100)),
                ("future_scope", models.TextField()),
            ],
        ),
    ]
